package com.nelyan_live.modals.myads

data class MyAdsData(
        val activityimages: ArrayList<Activityimage>,
        val activityname: String,
        val adMsg: String,
        val addInfo: String,
        val address: String,
        val ageGroups: ArrayList<AgeGroup>,
        val availablePlace: String,
        val categoryId: Int,
        val city: String,
        val countryCode: String,
        val country_code: String,
        val createdAt: String,
        val description: String,
        val events: ArrayList<Any>,
        val id: Int,
        val isPublished: Int,
        val ispublished: Int,
        val latitude: String,
        val longitude: String,
        val name: String,
        val nameOfShop: String,
        val nurseryimages: ArrayList<Nurseryimage>,
        val nurseryasistantimages: ArrayList<NurseryAsistantimages>,
        val phone: String,
        val status: Int,
        val typeofActivityId: Int,
        val updatedAt: String,
        val userId: Int
)