package com.nelyanlive.modals.myFavourite

data class PostData(
    val ChildCareImages: ArrayList<ChildCareImage>,
    val ChildcareType: Int,
    val activityimages: ArrayList<Activityimage>,
    val activityname: String,
    val adMsg: String,
    val address: String,
    val availableplace: Int,
    val categoryId: Int,
    val city: String,
    val countryCode: String,
    val country_code: String,
    val createdAt: String,
    val dateFrom: String,
    val dateTo: String,
    val description: String,
    val email: String,
    val id: Int,
    val isPublished: Int,
    val ispublished: Int,
    val latitude: String,
    val longitude: String,
    val name: String,
    val nameOfShop: String,
    val phone: String,
    val status: Int,
    val tradername: String,
    val tradersimages: ArrayList<Tradersimage>,
    val type: Int,
    val typeofActivityId: Int,
    val typeofTraderId: Int,
    val updatedAt: String,
    val userId: Int,
    val website: String,
    val isFav: Int
)